
Partial Class Patrons_EditAccount
    Inherits System.Web.UI.Page
    'In most real-world scenarios, this page will be disabled, legally, librarians have to verify 
    'home addresses through proof of residence. This is just here so that the option is availible, 
    'consider it an optional part of the program.
    Dim LibraryUser As ProfileBase
    Dim CurrentUserProfile As ProfileBase

    'So, funny story about this section. 
    'According to the official MSDN documentation of Visual Studio 2010,
    'ASP.NET will allow you to access profile properties via Profile.City or what have you.
    'The way in which it does this is by creating an instance of the ProfileCommon class, 
    'which is a modified version of the ProfileBase class that has additional functionality
    '(so that you don't have to keep calling GetPropertyValue).
    'However, what MSDN doesn't tell you is that, while all ASP.NET projects will generate the 
    'ProfileCommon class, only one of the potential project templates actually connects the 
    'ProfileCommon class to the database. So, if, when you started your project, you selected 
    '"ASP.NET Web Application", this functionality is not present, and you have to access profile
    'information through repeated calls of GetPropertyValue, and the profile has to be accessed through
    'HttpContext instead of the autogenerated stuff. It's a pain in the you know what, but that's
    'why this particular section is so messy-looking.

    Protected Sub SqlDataSource1_Selecting(sender As Object, e As System.Web.UI.WebControls.SqlDataSourceSelectingEventArgs) Handles SqlDataSource1.Selecting
        Dim currentUser As MembershipUser
        Dim id As Guid
        currentUser = Membership.GetUser()
        id = currentUser.ProviderUserKey

        e.Command.Parameters("@PatronID").Value = id

    End Sub



    Protected Sub Page_Load(sender As Object, e As System.EventArgs) Handles Me.Load
        Dim dview As New Data.DataView
        Dim LibraryID As Guid

        dview = CType(SqlDataSource1.Select(DataSourceSelectArguments.Empty), Data.DataView)
        LibraryID = CType(dview.Table.Rows.Item(0).Item("LibraryID"), Guid)
        LibraryUser = Profile.GetProfile(Membership.GetUser(LibraryID).UserName)

        CardNumberLabel.Text = CType(dview.Table.Rows.Item(0).Item("LibraryCard"), String)
        LibraryNameLabel.Text = LibraryUser.GetPropertyValue("FullName")

        CurrentUserProfile = HttpContext.Current.Profile



        If Not (Page.IsPostBack) Then

            NameLabel.Text = CurrentUserProfile.GetPropertyValue("FullName")
            AddressTextbox.Text = CurrentUserProfile.GetPropertyValue("Address")
            CityTextbox.Text = CurrentUserProfile.GetPropertyValue("City")
            StateTextbox.Text = CurrentUserProfile.GetPropertyValue("State")
            CountryTextbox.Text = CurrentUserProfile.GetPropertyValue("Country")
            ZipTextbox.Text = CurrentUserProfile.GetPropertyValue("Zip")
            PhoneTextbox.Text = CurrentUserProfile.GetPropertyValue("Phone")

        End If


    End Sub


    Protected Sub SaveButton_Click(sender As Object, e As System.EventArgs) Handles SaveButton.Click


        CurrentUserProfile.SetPropertyValue("Address", AddressTextbox.Text)
        CurrentUserProfile.SetPropertyValue("City", CityTextbox.Text)
        CurrentUserProfile.SetPropertyValue("State", StateTextbox.Text)
        CurrentUserProfile.SetPropertyValue("Country", CountryTextbox.Text)
        CurrentUserProfile.SetPropertyValue("Zip", ZipTextbox.Text)
        CurrentUserProfile.SetPropertyValue("Phone", PhoneTextbox.Text)

        CurrentUserProfile.Save()


        SavedLabel.Visible = True
    End Sub
End Class
